parameters:
#    saa_s_info_manager_core.example.class: SaaSInfoManager\Bundle\CoreBundle\Example
    sf.serializer.class: Symfony\Component\Serializer\Serializer
    sf.jsonEncoder.class: Symfony\Component\Serializer\Encoder\JsonEncoder;
    sf.getterSetterNormalizer.class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer;

services:
#    saa_s_info_manager_core.example:
#        class: %saa_s_info_manager_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    saas_im_core.serilizer:
        class: %sf.serializer.class%
        arguments: [[%sf.jsonEncoder.class%], [%sf.getterSetterNormalizer.class%]]
