SaaSInfoManager\Bundle\InfoManagerBundle\Entity\Client:
    type: entity
    table: null
    repositoryClass: SaaSInfoManager\Bundle\InfoManagerBundle\Entity\ClientRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
        email:
            type: string
            length: '100'
        contactNumber:
            type: string
            length: '20'
            column: contact_number
        address1:
            type: string
            length: '100'
        address2:
            type: string
            length: '100'
        city:
            type: string
            length: '100'
        countryId:
            type: integer
            column: country_id
    lifecycleCallbacks: {  }
