<?php

namespace SaaSInfoManager\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IndustryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndustryRepository extends EntityRepository
{
}
