SaaSInfoManager\Bundle\CoreBundle\Entity\Country:
    type: entity
    table: country
    repositoryClass: SaaSInfoManager\Bundle\CoreBundle\Entity\CountryRepository
    id:
        code:
            type: string
            legnth: '2'
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '150'
    lifecycleCallbacks: {  }
